CREATE TABLE spotify_tracks (
    track_id VARCHAR(50),
    artists TEXT,
    album_name TEXT,
    track_name TEXT,
    popularity INTEGER,
    duration_ms INTEGER,
    explicit BOOLEAN,
    danceability DOUBLE PRECISION,
    energy DOUBLE PRECISION,
    key INTEGER,
    loudness DOUBLE PRECISION,
    mode INTEGER,
    speechiness DOUBLE PRECISION,
    acousticness DOUBLE PRECISION,
    instrumentalness DOUBLE PRECISION,
    liveness DOUBLE PRECISION,
    valence DOUBLE PRECISION,
    tempo DOUBLE PRECISION,
    time_signature INTEGER,
    track_genre VARCHAR(50),
    duration_min DOUBLE PRECISION,
    popularity_level VARCHAR(20),

    PRIMARY KEY (track_id, track_genre)
);